export const USERINFO_UPDATE = 'USERINFO_UPDATE';
export const START_FETCH = 'START_FETCH';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_END = 'FETCH_END';
export const GET_USER_LOCATION = 'GET_USER_LOCATION';